name: Build and publish API docs

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Haxe 4.3.7
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Prepare haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install dox --always

      - name: Build API docs (test)
        run: haxe doc.hxml

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: bin/api

  publish-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: api-docs
          path: bin/api

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bin/api
          publish_branch: gh-pages
